export const STORE_GROUPS = 'STORE_GROUPS';
export const SELECT_CURRENT_CHANNEL = 'SELECT_CURRENT_CHANNEL';
export const STORE_ONLINE_USERS='STORE_ONLINE_USERS';
export const STORE_ALL_MESSAGES='STORE_ALL_MESSAGES';
export const STORE_SENDING_QUEUE='STORE_SENDING_QUEUE';
export const STORE_ALL_USERS='STORE_ALL_USERS'
export const STORE_TYPING_USERS='STORE_TYPING_USERS';
export const STORE_FILE_OBJECT='STORE_FILE_OBJECT';
export const CLEAR_ALL_DATA='CLEAR_ALL_DATA';





